### ISSUE TITLE
Contact author of original blog post

### ISSUE THREAD

**Issue by mkrogemann** [codecurious-bln/elixir_snake#3]
I think we should contact the author and let them know what we are planning to do.
I do not expect any negative reactions but want to make sure we do not forget about the important contribution that was made by the author.
I am more than happy to execute on this task myself. Just adding it here for now so we don't forget to do it.

**Comment by jvf** [comment]
That would be awesome!

**Comment by ggpasqualino** [comment]
I sort of contacted him in order to clarify #6
