### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by jvf** [codecurious-bln/elixir_snake#6]
Do we need to add a licence? I am never sure about this. Personally I like BSD-style licences, but I do not have strongly hold opinions here.

The [repo](https://github.com/gVirtu/scenic-snake) of the  [original tutorial](https://blog.usejournal.com/elixir-scenic-snake-game-b8616b1d7ee0) does not have a licence attached.

**Comment by klappradla** [comment]
Good point!

I personally feel that any repo one uses in a slightly _"professional"_ context - as in it is likely that multiple random people will look at it - needs a license to make it _"official enough"_.

So yes, throwing in a BSD-2 or an MIT sound solid in my opinion. They are more or less the same, MIT just makes it even more obvious that anything can be done with the code.

Going for a 3 or 4 clause BSD license sounds a bit wrong to me if we're already heavily basing our ideas on an existing tutorial (that may also be composed from other sources).

**Comment by ggpasqualino** [comment]
> The repo of the original tutorial does not have a licence attached.

😬 

We should definitely move forward with #3 then. According to https://choosealicense.com/no-permission/ 
> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

**Comment by ggpasqualino** [comment]
I opened this issue in the original repo https://github.com/gVirtu/scenic-snake/issues/2

**Comment by ggpasqualino** [comment]
Ok, the original one has an MIT license now

**Comment by jvf** [comment]
Should we use MIT licence as well then?

**Comment by klappradla** [comment]
Yep, sounds the most straight forward to me. I added one via the web UI in #8
